apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: go-nhysikeo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-nhysikeo 
  name: go-nhysikeo
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: go-nhysikeo 
